<a href="https://colab.research.google.com/github/hectorjimenez12/CC5205_Proyecto/blob/main/Hito2/01_Deteccion_Variable_Que_Hace_Exitoso_Juego.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import requests
import seaborn as sns
import datetime
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
pd.set_option('display.max_columns', 50)

Importar datos utiles de juegos de Steam

In [2]:
url = 'https://raw.githubusercontent.com/hectorjimenez12/Mineria_Datos/main/steam.csv'
df = pd.read_csv(url)
df.head()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99

In [3]:
df = df.astype({'english':object,'required_age':object})
print('Info:')
print(df.info())
types_data = df.dtypes.values

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appid             27075 non-null  int64
 1   name              27075 non-null  object
 2   release_date      27075 non-null  object
 3   english           27075 non-null  object
 4   developer         27075 non-null  object
 5   publisher         27075 non-null  object
 6   platforms         27075 non-null  object
 7   required_age      27075 non-null  object
 8   categories        27075 non-null  object
 9   genres            27075 non-null  object
 10  steamspy_tags     27075 non-null  object
 11  achievements      27075 non-null  int64
 12  positive_ratings  27075 non-null  int64
 13  negative_ratings  27075 non-null  int64
 14  average_playtime  27075 non-null  int64
 15  median_playtime   27075 non-null  int64
 16  owners            27075 non-null  object
 17  price             27075 non-null  float64
dtypes: float64(1), int64(6), object(11)
memory usage: 3.7+ MB
None

In [4]:
num_data = df[ [ df.columns[i] for i in range(len(types_data)) if types_data[i] != object  ]  ]
print('Resumen de Atributos Numericos:')
num_data['pos_r/tot_r'] = np.array(num_data['positive_ratings'])/(np.array(num_data['positive_ratings'])+np.array(num_data['negative_ratings']))
numerical_successfull_var = ['por_r/tot_r']
num_data.describe()

Resumen de Atributos Numericos:

<ipython-input-4-b6a38dfd4654>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  num_data['pos_r/tot_r'] = np.array(num_data['positive_ratings'])/(np.array(num_data['positive_ratings'])+np.array(num_data['negative_ratings']))

,appid,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,price,pos_r/tot_r
count,2.707500e+04,27075.000000,2.707500e+04,27075.000000,27075.000000,27075.00000,27075.000000,27075.000000
mean,5.962035e+05,45.248864,1.000559e+03,211.027147,149.804949,146.05603,6.078193,0.714478
std,2.508942e+05,352.670281,1.898872e+04,4284.938531,1827.038141,2353.88008,7.874922,0.233594
min,1.000000e+01,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000
25%,4.012300e+05,0.000000,6.000000e+00,2.000000,0.000000,0.00000,1.690000,0.583333
50%,5.990700e+05,7.000000,2.400000e+01,9.000000,0.000000,0.00000,3.990000,0.760331
75%,7.987600e+05,23.000000,1.260000e+02,42.000000,0.000000,0.00000,7.190000,0.893905
max,1.069460e+06,9821.000000,2.644404e+06,487076.000000,190625.000000,190625.00000,421.990000,1.000000

### Analisis de variable razón de positive rating sobre total ratings:

In [5]:
plt.scatter(y =df['pos_r/tot_r'])

NameError: ignored

Useful functions for downloading data.